# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='tank_volume',
        ),
        migrations.AddField(
            model_name='tank',
            name='tank_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
